# Generated by Django 4.0.6 on 2022-07-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='')),
            ],
            options={
                'db_table': 'back_img',
            },
        ),
        migrations.CreateModel(
            name='BottomCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='')),
                ('link', models.URLField(default='', verbose_name='')),
            ],
            options={
                'db_table': 'bottom_carousel',
            },
        ),
        migrations.CreateModel(
            name='CafeBarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('weight', models.PositiveIntegerField(null=True, verbose_name='Вес(грамм)')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='Цена')),
            ],
            options={
                'db_table': 'cafe_bar_menu',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('banner', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер')),
                ('logo', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Логотип')),
            ],
            options={
                'db_table': 'cinema',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'editors',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('card_img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка карточки')),
                ('released', models.DateField(verbose_name='Дата выхода')),
                ('trailer_link', models.URLField(max_length=100, verbose_name='Ссылка на трейлер')),
                ('banner', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('budget', models.CharField(max_length=15, verbose_name='Бюджет')),
                ('legal_age', models.PositiveIntegerField(verbose_name='Мин Возраст')),
                ('duration', models.CharField(max_length=15, verbose_name='Длительность')),
                ('countries', models.ManyToManyField(to='admin_panel.country', verbose_name='Страны')),
                ('editors', models.ManyToManyField(to='admin_panel.editor', verbose_name='Режисёры')),
            ],
            options={
                'db_table': 'films',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер зала')),
                ('banner', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('num_tickets', models.PositiveSmallIntegerField(verbose_name='Кол-во биллетов')),
                ('scheme', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Cхема зала')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('cinema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cinema')),
            ],
            options={
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('short_description', models.TextField(default='', max_length=50, verbose_name='Краткое описание')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('turn_on', models.BooleanField(default=False, verbose_name='ВКЛ/ВЫКЛ')),
                ('video_link', models.URLField(verbose_name='Ссылка на видео')),
                ('banner', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер')),
                ('card_img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка карточки')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'operators',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('banner', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер')),
                ('first_pic', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Первая картинка')),
                ('second_pic', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Вторая картинка')),
                ('third_pic', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Третья картинка')),
                ('description2', models.TextField(default='', verbose_name='Второе описание')),
                ('turn_on', models.BooleanField(default=False, verbose_name='ВКЛ/ВЫКЛ')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('able_to_del', models.BooleanField(default=True)),
                ('cinema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cinema')),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'producers',
            },
        ),
        migrations.CreateModel(
            name='ScriptWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scriptwriters',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(verbose_name='%H:%M')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.hall')),
            ],
            options={
                'db_table': 'seances',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=150, verbose_name='Ссылка')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('seo_description', models.TextField(null=True, verbose_name='Описание')),
                ('keywords', models.CharField(max_length=255, verbose_name='Ключевые слова')),
            ],
            options={
                'db_table': 'seo_block',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('short_description', models.TextField(default='', max_length=50, verbose_name='Краткое описание')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('turn_on', models.BooleanField(default=False, verbose_name='ВКЛ/ВЫКЛ')),
                ('video_link', models.URLField(verbose_name='Ссылка на видео')),
                ('banner', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер')),
                ('card_img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка карточки')),
                ('seo_block', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='TechnologyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'technology_type',
            },
        ),
        migrations.CreateModel(
            name='TopCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='')),
                ('link', models.URLField(default='', verbose_name='')),
                ('title', models.CharField(default='', max_length=50, verbose_name='')),
            ],
            options={
                'db_table': 'top_carousel',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name=' Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name=' Фамилия')),
                ('nickname', models.CharField(max_length=40, unique=True, verbose_name=' Логин')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=200, verbose_name=' Адрес')),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Мужской', max_length=20, verbose_name='Пол')),
                ('lang', models.CharField(choices=[('Русский', 'Русский'), ('Украинскийй', 'Украинский')], default='Русский', max_length=20, verbose_name='Язык')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('birthday', models.DateField(verbose_name='День Рождения')),
                ('password', models.CharField(max_length=20, verbose_name=' Пароль')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField()),
                ('row', models.PositiveSmallIntegerField()),
                ('seat', models.PositiveSmallIntegerField()),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seance')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='StockImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.stock')),
            ],
            options={
                'db_table': 'stock_imgs',
            },
        ),
        migrations.AddField(
            model_name='seance',
            name='tech_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.technologytype'),
        ),
        migrations.CreateModel(
            name='PageImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.page')),
            ],
            options={
                'db_table': 'pages_imgs',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock'),
        ),
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.news')),
            ],
            options={
                'db_table': 'news_imgs',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock'),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('number2', models.CharField(max_length=100, unique=True)),
                ('seo_text', models.TextField(default='')),
                ('seo_block', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock')),
            ],
            options={
                'db_table': 'main_page',
            },
        ),
        migrations.CreateModel(
            name='HallImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.hall')),
            ],
            options={
                'db_table': 'halls_imgs',
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock'),
        ),
        migrations.CreateModel(
            name='FilmImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.film')),
            ],
            options={
                'db_table': 'film_imgs',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='admin_panel.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='film',
            name='operators',
            field=models.ManyToManyField(to='admin_panel.operator', verbose_name='Операторы'),
        ),
        migrations.AddField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(to='admin_panel.producer', verbose_name='Продюсеры'),
        ),
        migrations.AddField(
            model_name='film',
            name='scriptwriters',
            field=models.ManyToManyField(to='admin_panel.scriptwriter', verbose_name='Сценаристы'),
        ),
        migrations.AddField(
            model_name='film',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock'),
        ),
        migrations.AddField(
            model_name='film',
            name='technology_types',
            field=models.ManyToManyField(to='admin_panel.technologytype', verbose_name='Форматы'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('coordinate', models.TextField(max_length=10000)),
                ('logo', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/')),
                ('cinema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cinema')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.user')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='CinemaImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cinema')),
            ],
            options={
                'db_table': 'cinema_imgs',
            },
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock'),
        ),
    ]
